### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by Firstyear** [uncomfyhalomacro/obs-service-cargo_vendor-rs#8]
Due to how rust works, GPL can be a bit problematic because of it's linking conditions and clauses. The majority of the rust community generally has settled on MIT (permissive) or MPL2 (copyleft) as the default licenses. Alternately, consider the LGPL2 that omits the linking clauses that cause issues. I'm not a lawyer, but I've been lectured about this in the past when I created other rust libraries.

**Comment by uncomfyhalomacro** [comment]
Got the same idea. I will change it later

**Comment by uncomfyhalomacro** [comment]
Completed at commit https://github.com/uncomfyhalomacro/obs-service-cargo_vendor-rs/commit/811c1386614559a17d6bf176701eabb38e139cca
